### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by johnnyschneider** [jemcek/packETH#23]
Hi! I'm interested in using this software for a project. Attempted to build on an Ubuntu 20.04 system, and the build fails with the error seen here.

```
gcc  -g -O2   -o packETH src/main.o src/support.o src/interface.o src/callbacks.o src/function.o src/function_send.o src/loadpacket.o src/savepacket.o  -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lharfbuzz -lfontconfig -lfreetype -lgthread-2.0 -pthread -lglib-2.0 -lm
/usr/bin/ld: src/function_send.o:/home/johnathan/Documents/packeth/src/function_send.c:58: multiple definition of `iftext'; src/callbacks.o:/home/johnathan/Documents/packeth/src/callbacks.c:68: first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:477: packETH] Error 1

```

**Comment by jemcek** [comment]
Hi Jonathan, 

I will take a look. I never tested on Ubuntu 20.04, so I don’t know if anything changed from 18.04. 

Did you follow the instruction about installation ob Github?

Regards, Miha

**Comment by johnnyschneider** [comment]
Yes! I made a small recording the start to finish of calling git clone, calling all the commands, and the build fail. See here https://youtu.be/KvJJcCGP_8Q

**Comment by jemcek** [comment]
Hi Jonathan, 

I just made a fresh installation of Ubunto 20.04 deskop and then followed the commands in this order as stated on the github. I didn’t have any problems isntalling packeth

sudo apt install git
git clone https://github.com/jemcek/packETH.git
cd packETH/
sudo apt-get install build-essential
sudo apt-get install autoconf
sudo apt-get install pkg-config
sudo apt-get install gtk+2.0
./autogen.sh 
./configure 
make
./packETH 

Additional installation of aclocal, autoheader and automake was not necessary since they were already installed with autoconf. 

So I don’t have any idea what could be different on your system. Maybe you did some other isntallations in the past that could ruin the lib dependencies for packeth.
So I can only suggest you to try a fresh installation and try again. 

Also you could run "autoreconf -f -i “ after autogen.sh this helps sometimes if some files are broken. 

Regards, Miha
